import UIKit

struct Characters {
    var characters: [Character]
    var total: Int?
    
    // Receives the struct generated by the user service parser
    init(charactersEntity: [CharacterEntity], total: Int?) {
        self.total = total
        
        var characters = [Character]()
        
        for characterEntity in charactersEntity {
            guard let character = Character(character: characterEntity) else { continue }
            characters.append(character)
        }
        
        self.characters = characters
    }
}

struct Character {
    let id: UInt
    let name: String
    let description: String?
    let thumbnail: String?
    
    init?(character: CharacterEntity) {
        guard let id  = character.id, let name = character.name else { return nil }
        self.id = id
        self.name = name
        description = character.description
        if let path = character.thumbnail?.path,
            let extensionFile = character.thumbnail?.extensionFile {
            thumbnail = "\(path).\(extensionFile)"
        } else {
            thumbnail = nil
        }
    }
}
